language: ruby
rvm:
 - 2.6.3
services:
- postgresql
before_install:
  - sudo apt-get install postgresql-9.6 postgresql-server-dev-9.6 libpq-dev
  - gem install do_postgres
install:
  - bundle install
before_script:
   - psql -c 'create database quizzical_test;' -U postgres
script:
- bundle exec rake db_populate
- bundle exec rspec
