language: ruby
rvm:
 - 2.6.3
services:
- postgresql
addons:
  postgresql: "11.5"
before_install:
  - gem install -v 1.17.3 bundler
  - sudo apt-get install postgresql-9.5 postgresql-server-dev-9.5 libpq-dev
  - gem install do_postgres
install:
  - bundle install
before_script:
   - psql -c 'create database quizzical_test;' -U postgres
script:
- bundle exec rake db_populate
- bundle exec rspec
