language: ruby
rvm:
 - 2.6.5
services:
- postgresql
before_install:
- gem install do_postgres -v '0.10.16'
install:
  - bundle install
script:
- bundle exec rake db_create_and_populate
- bundle exec rspec
