language: ruby
rvm:
 - 2.6.3
services:
- postgresql
addons:
  postgresql: "11.5"
before_install:
  - sudo apt-get install postgresql-9.5 postgresql-server-dev-9.5 libpq-dev
  - gem install do_postgres -v '0.10.17' --source
install:
  - bundle install
script:
- bundle install
- bundle exec rake db_create_and_populate
- bundle exec rspec
