language: ruby
rvm:
 - 2.6.3
services:
- postgresql
addons:
  postgresql: "11.5"
before_install:
  - sudo apt-get install postgresql-server-dev-10
  - gem install do_postgres
install:
  - bundle install
before_script:
   - psql -c 'create database quizzical_test;' -U postgres
script:
- bundle exec rake db_populate
- bundle exec rspec
